WITH cleaned AS (
    SELECT
        raw_id,
        NULLIF(BTRIM(arquivo_origem), '') AS arquivo_origem,
        NULLIF(BTRIM(ano_arquivo), '') AS ano_arquivo,
        NULLIF(BTRIM(tp_not), '') AS tp_not,
        NULLIF(BTRIM(id_agravo), '') AS id_agravo,
        NULLIF(BTRIM(dt_notific), '') AS dt_notific,
        NULLIF(BTRIM(sem_not), '') AS sem_not,
        NULLIF(BTRIM(nu_ano), '') AS nu_ano,
        NULLIF(BTRIM(sg_uf_not), '') AS sg_uf_not,
        NULLIF(BTRIM(id_municip), '') AS id_municip,
        NULLIF(BTRIM(id_regiona), '') AS id_regiona,
        NULLIF(BTRIM(dt_sin_pri), '') AS dt_sin_pri,
        NULLIF(BTRIM(sem_pri), '') AS sem_pri,
        NULLIF(BTRIM(nu_idade_n), '') AS nu_idade_n,
        UPPER(NULLIF(BTRIM(cs_sexo), '')) AS cs_sexo,
        NULLIF(BTRIM(cs_gestant), '') AS cs_gestant,
        NULLIF(BTRIM(cs_raca), '') AS cs_raca,
        NULLIF(BTRIM(cs_escol_n), '') AS cs_escol_n,
        NULLIF(BTRIM(sg_uf), '') AS sg_uf,
        NULLIF(BTRIM(id_mn_resi), '') AS id_mn_resi,
        NULLIF(BTRIM(id_rg_resi), '') AS id_rg_resi,
        NULLIF(BTRIM(id_pais), '') AS id_pais,
        NULLIF(BTRIM(nduplic_n), '') AS nduplic_n,
        NULLIF(BTRIM(in_vincula), '') AS in_vincula,
        NULLIF(BTRIM(dt_invest), '') AS dt_invest,
        NULLIF(BTRIM(id_ocupa_n), '') AS id_ocupa_n,
        NULLIF(BTRIM(classi_fin), '') AS classi_fin,
        NULLIF(BTRIM(criterio), '') AS criterio,
        NULLIF(BTRIM(tpautocto), '') AS tpautocto,
        NULLIF(BTRIM(coufinf), '') AS coufinf,
        NULLIF(BTRIM(copaisinf), '') AS copaisinf,
        NULLIF(BTRIM(comuninf), '') AS comuninf,
        NULLIF(BTRIM(doenca_tra), '') AS doenca_tra,
        NULLIF(BTRIM(evolucao), '') AS evolucao,
        NULLIF(BTRIM(dt_obito), '') AS dt_obito,
        NULLIF(BTRIM(dt_encerra), '') AS dt_encerra,
        NULLIF(BTRIM(cs_flxret), '') AS cs_flxret,
        NULLIF(BTRIM(flxrecebi), '') AS flxrecebi,
        NULLIF(BTRIM(tp_sistema), '') AS tp_sistema,
        NULLIF(BTRIM(tpuninot), '') AS tpuninot,
        NULLIF(BTRIM(id_unidade), '') AS id_unidade,
        NULLIF(BTRIM(ano_nasc), '') AS ano_nasc,
        NULLIF(BTRIM(dt_digita), '') AS dt_digita,
        row_hash,
        is_duplicate
    FROM staging.notificacoes_zika_raw
),
typed AS (
    SELECT
        *,
        CASE WHEN ano_arquivo ~ '^[0-9]+$' THEN ano_arquivo::SMALLINT END AS ano_arquivo_int,
        CASE WHEN tp_not ~ '^[0-9]+$' THEN tp_not::SMALLINT END AS tp_not_int,
        CASE WHEN sem_not ~ '^[0-9]+$' THEN sem_not::INTEGER END AS sem_not_int,
        CASE WHEN nu_ano ~ '^[0-9]+$' THEN nu_ano::SMALLINT END AS nu_ano_int,
        CASE WHEN sg_uf_not ~ '^[0-9]+$' THEN sg_uf_not::SMALLINT END AS sg_uf_not_int,
        CASE WHEN id_municip ~ '^[0-9]+$' THEN id_municip::INTEGER END AS id_municip_int,
        CASE WHEN sem_pri ~ '^[0-9]+$' THEN sem_pri::INTEGER END AS sem_pri_int,
        CASE WHEN nu_idade_n ~ '^[0-9]+$' THEN SUBSTRING(nu_idade_n FROM 1 FOR 1)::SMALLINT END AS idade_unidade_int,
        CASE WHEN nu_idade_n ~ '^[0-9]+$' THEN SUBSTRING(nu_idade_n FROM 2)::SMALLINT END AS idade_quantidade_int,
        CASE WHEN cs_gestant ~ '^[0-9]+$' THEN cs_gestant::SMALLINT END AS cs_gestant_int,
        CASE WHEN cs_raca ~ '^[0-9]+$' THEN cs_raca::SMALLINT END AS cs_raca_int,
        CASE WHEN cs_escol_n ~ '^[0-9]+$' THEN cs_escol_n::SMALLINT END AS cs_escol_n_int,
        CASE WHEN sg_uf ~ '^[0-9]+$' THEN sg_uf::SMALLINT END AS sg_uf_int,
        CASE WHEN id_mn_resi ~ '^[0-9]+$' THEN id_mn_resi::INTEGER END AS id_mn_resi_int,
        CASE WHEN classi_fin ~ '^[0-9]+$' THEN classi_fin::SMALLINT END AS classi_fin_int,
        CASE WHEN criterio ~ '^[0-9]+$' THEN criterio::SMALLINT END AS criterio_int,
        CASE WHEN tpautocto ~ '^[0-9]+$' THEN tpautocto::SMALLINT END AS tpautocto_int,
        CASE WHEN coufinf ~ '^[0-9]+$' THEN coufinf::SMALLINT END AS coufinf_int,
        CASE WHEN comuninf ~ '^[0-9]+$' THEN comuninf::INTEGER END AS comuninf_int,
        CASE WHEN doenca_tra ~ '^[0-9]+$' THEN doenca_tra::SMALLINT END AS doenca_tra_int,
        CASE WHEN evolucao ~ '^[0-9]+$' THEN evolucao::SMALLINT END AS evolucao_int,
        CASE WHEN ano_nasc ~ '^[0-9]+$' THEN ano_nasc::SMALLINT END AS ano_nasc_int,
        CASE WHEN dt_notific ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}$' THEN dt_notific::DATE END AS dt_notific_date,
        CASE WHEN dt_sin_pri ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}$' THEN dt_sin_pri::DATE END AS dt_sin_pri_date,
        CASE WHEN dt_invest ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}$' THEN dt_invest::DATE END AS dt_invest_date,
        CASE WHEN dt_obito ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}$' THEN dt_obito::DATE END AS dt_obito_date,
        CASE WHEN dt_encerra ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}$' THEN dt_encerra::DATE END AS dt_encerra_date,
        CASE WHEN dt_digita ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}$' THEN dt_digita::DATE END AS dt_digita_date
    FROM cleaned
),
decoded AS (
    SELECT
        *,
        CASE idade_unidade_int
            WHEN 1 THEN 0
            WHEN 2 THEN 0
            WHEN 3 THEN FLOOR(idade_quantidade_int / 12.0)::INTEGER
            WHEN 4 THEN idade_quantidade_int::INTEGER
        END AS idade_anos_int
    FROM typed
)
INSERT INTO core.notificacao_zika (
    raw_id,
    arquivo_origem,
    ano_arquivo,
    tp_not,
    id_agravo,
    dt_notific,
    sem_not,
    nu_ano,
    uf_notificacao,
    municipio_notificacao,
    regional_notificacao,
    dt_sin_pri,
    sem_pri,
    nu_idade_n,
    idade_unidade,
    idade_quantidade,
    idade_anos,
    sexo_codigo,
    gestante_codigo,
    raca_codigo,
    escolaridade_codigo,
    uf_residencia,
    municipio_residencia,
    regional_residencia,
    pais_residencia,
    nduplic_codigo,
    in_vincula,
    dt_invest,
    ocupacao_cbo,
    classi_fin_codigo,
    criterio_codigo,
    tpautocto_codigo,
    uf_infeccao,
    pais_infeccao,
    municipio_infeccao,
    doenca_trabalho_codigo,
    evolucao_codigo,
    dt_obito,
    dt_encerra,
    cs_flxret,
    flxrecebi,
    tp_sistema,
    tpuninot,
    id_unidade,
    ano_nasc,
    dt_digita,
    row_hash,
    is_duplicate
)
SELECT
    raw_id,
    COALESCE(arquivo_origem, 'sem_origem'),
    ano_arquivo_int,
    tp_not_int,
    id_agravo,
    dt_notific_date,
    sem_not_int,
    nu_ano_int,
    CASE WHEN sg_uf_not_int IN (11,12,13,14,15,16,17,21,22,23,24,25,26,27,28,29,31,32,33,35,41,42,43,50,51,52,53) THEN sg_uf_not_int END,
    id_municip_int,
    id_regiona,
    dt_sin_pri_date,
    sem_pri_int,
    nu_idade_n,
    CASE WHEN idade_unidade_int IN (1,2,3,4) THEN idade_unidade_int END,
    idade_quantidade_int,
    idade_anos_int,
    CASE WHEN cs_sexo IN ('M', 'F', 'I') THEN cs_sexo END,
    CASE WHEN cs_gestant_int IN (1,2,3,4,5,6,9) THEN cs_gestant_int END,
    CASE WHEN cs_raca_int IN (1,2,3,4,5,9) THEN cs_raca_int END,
    CASE WHEN cs_escol_n_int IN (0,1,2,3,4,5,6,7,8,9,10) THEN cs_escol_n_int END,
    CASE WHEN sg_uf_int IN (11,12,13,14,15,16,17,21,22,23,24,25,26,27,28,29,31,32,33,35,41,42,43,50,51,52,53) THEN sg_uf_int END,
    id_mn_resi_int,
    id_rg_resi,
    id_pais,
    nduplic_n,
    in_vincula,
    dt_invest_date,
    id_ocupa_n,
    CASE WHEN classi_fin_int IN (0,1,2,8) THEN classi_fin_int END,
    CASE WHEN criterio_int IN (0,1,2) THEN criterio_int END,
    CASE WHEN tpautocto_int IN (1,2,3) THEN tpautocto_int END,
    CASE WHEN coufinf_int IN (11,12,13,14,15,16,17,21,22,23,24,25,26,27,28,29,31,32,33,35,41,42,43,50,51,52,53) THEN coufinf_int END,
    copaisinf,
    comuninf_int,
    CASE WHEN doenca_tra_int IN (0,1,2,9) THEN doenca_tra_int END,
    CASE WHEN evolucao_int IN (0,1,2,3,9) THEN evolucao_int END,
    dt_obito_date,
    dt_encerra_date,
    cs_flxret,
    flxrecebi,
    tp_sistema,
    tpuninot,
    id_unidade,
    ano_nasc_int,
    dt_digita_date,
    row_hash,
    is_duplicate
FROM decoded
WHERE NOT EXISTS (
    SELECT 1
    FROM core.notificacao_zika existing
    WHERE existing.raw_id = decoded.raw_id
);
